### ISSUE TITLE
UnicodeDecodeError when using layout files with arrow characters

### ISSUE THREAD

**Issue by MrIamsosmrt** [jeffminton/keyboard_stl_generator#1]
When using the program with a layout file that has arrow characters (↑, ←, ↓, →) it doesn't work and reports an error message:

>   File "C:\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 1134: character maps to \<undefined\>

**Comment by jeffminton** [comment]
What version of python are you using? Also can you post the layout file you were using?

**Comment by MrIamsosmrt** [comment]
I'm using python 3.10.2

Here's the layout file:

[numpad_with_error.txt](https://github.com/jeffminton/keyboard_stl_generator/files/8056770/numpad_with_error.txt)

**Comment by jeffminton** [comment]
Did you mean to close the issue? Did you figure out the issue? I am having trouble installing SolidPython in python 3.10
