### ISSUE TITLE
Missing angled keys and some artefacts

### ISSUE THREAD

**Issue by pvcdx** [jeffminton/keyboard_stl_generator#5]
Hello,

testing the included layouts, command

./keyboard_stl_generator.py -a -i layout_files/ergodox_named.json

produces files that render with extra lines the width of the whole keyboard, and the angled thumb cluster keys missing

![ergodox_named_section_0_all 1](https://user-images.githubusercontent.com/47482590/171936408-91805d2a-215c-4488-885a-9c2950daaaff.png)

Could You please have a look at it?

**Comment by jeffminton** [comment]
Yes I see the issue as well. I will work on it when I get some time and let you know when to try again

**Comment by jeffminton** [comment]
I believe I have corrected the issue. Please try it again

**Comment by pvcdx** [comment]
Thank You for the quick replay.

The thumb cluster appeared, but the two walls, crossing the printer board size boundary, are still there:
![ergodox_named_section_0_all 2](https://user-images.githubusercontent.com/47482590/171990285-53ef89d1-cfa2-4f37-a159-6a18c19081c0.png)

**Comment by jeffminton** [comment]
I put up another change that should address those bars that are showing up

**Comment by pvcdx** [comment]
The bars are fixed also..

Thank You!
